language: node_js
node_js:
    - "0.10"
before_install:
    - gem update --system
    - gem install sass --version 3.3.0
    - gem install compass --version 1.0.0.alpha.19
    - gem install susy --version 2.0.0
    - gem install modular-scale
